apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  template:
    spec:
      containers:
      - name: application
        env:
        - name: WORDPRESS_DB_HOST
          value: APP
