apiVersion: skaffold/v1
kind: Config
metadata:
  name: application-
build:
  artifacts:
  - image: opencv
    sync:
      manual:
      - src: 'src/**/*.py'
        dest: .
        strip: src/
      - src: 'src/static/**'
        dest: .
        strip: src/
  tagPolicy:
    dateTime: {}
deploy:
  # kustomize:
  #   path: .
  kubectl:
    manifests:
    - gen/*.yaml
    # - k8s/*
profiles:
- name: local
  activation:
  - env: KUBECONFIG=!
- name: incluster
  build:
    tagPolicy:
      dateTime: {}
    cluster:
      dockerConfig: 
        secretName: dockerconfig
