apiVersion: skaffold/v1
kind: Config
metadata:
  name: cvision-
build:
  artifacts:
  - image: dock-harbor.app.anton1.antondemo0101.dev.superhub.io/library/opencv
    sync:
      manual:
      - src: 'src/**/*.py'
        dest: .
        strip: src/
      - src: 'src/static/**'
        dest: .
        strip: src/
deploy:
  kubectl:
    manifests:
      - k8s/*
