apiVersion: skaffold/v1
build:
  artifacts:
  - image: detective
    sync:
      manual:
      - dest: /app
        src: src/**/*.py
        strip: src/
      - dest: /app
        src: src/static/**
        strip: src/
deploy:
  kubectl:
    manifests:
    - gen/*.yaml
kind: Config
metadata:
  name: detective-
profiles:
- activation:
  - env: KUBECONFIG=!
  build:
    local:
      useDockerCLI: true
  name: local
- build:
    cluster:
      dockerConfig:
        secretName: detective-dockerconfig
  name: incluster
